version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://exchange:exchange@db:5432/exchange
      - SECRET_KEY=dev-secret-key
      - ADMIN_API_KEY=dev-admin-key
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=exchange
      - POSTGRES_PASSWORD=exchange
      - POSTGRES_DB=exchange
      - POSTGRES_MAX_CONNECTIONS=200
    command: 
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=16MB"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exchange"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 