version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://exchange:exchange@db:5432/exchange
      - SECRET_KEY=dev-secret-key
      - ADMIN_API_KEY=dev-admin-key
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=exchange
      - POSTGRES_PASSWORD=exchange
      - POSTGRES_DB=exchange
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exchange"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 